#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  if [[ -t 0 || -t 1 ]]; then
    fortune -s
    print
  fi
fi

if [[ -z "$SSH_TTY" ]]; then
  ## Input settings
  # input_devices=$(xinput --list --name-only)

  # Keyboard settings
  # setxkbmap -layout pl,us -option ctrl:nocaps

  # # Touchpad settings
  # if [[ $input_devices =~ "SynPS/2 Synaptics TouchPad" ]]; then
  #   # finger tapping as clicks
  #   synclient TapButton1=1 TapButton2=2 TapButton3=3
  #   # natural scrolling
  #   synclient VertScrollDelta=-111 HorizScrollDelta=-111 \
  #             VertTwoFingerScroll=1 HorizTwoFingerScroll=1 \
  #             VertEdgeScroll=0 HorizEdgeScroll=0
  # fi
  #
  # # TrackPoint settings
  # if [[ $input_devices =~ "TPPS/2 IBM TrackPoint" ]]; then
  #   # vertical scrolling
  #   xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
  #   xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
  #   xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
  #   # horizontal scrolling
  #   xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
  # fi

  # User anacron
  if [[ -f ${HOME}/.anacron/etc/anacrontab ]]; then
    /usr/sbin/anacron -s -t ${HOME}/.anacron/etc/anacrontab -S ${HOME}/.anacron/spool
  fi
fi
