#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  fortune -a
  print
fi

# Keyboard settings
setxkbmap -layout pl,us -option ctrl:swapcaps

# Touchpad settings
if grep -q 'ThinkPad' /sys/class/dmi/id/product_version; then
  # finger tapping as clicks
  synclient TapButton1=1 TapButton2=2 TapButton3=3
  # natural scrolling
  synclient VertScrollDelta=-111 HorizScrollDelta=-111 \
            VertTwoFingerScroll=1 HorizTwoFingerScroll=1 \
            VertEdgeScroll=0 HorizEdgeScroll=0
fi
